### ISSUE TITLE
Keeps throwing an error

### ISSUE THREAD

**Issue by DamnMerc** [MartinRBX/rblx-js#1]
![image](https://user-images.githubusercontent.com/8603387/40393952-74949520-5def-11e8-8d9d-32fd538986c1.png)
Not really sure why it's doing this

**Comment by MartinRBX** [comment]
It is because you provided incorrect credentials when logging in.

**Comment by DamnMerc** [comment]
I highly doubt this, considering I used rbx-js before with the same information and never received any error regarding logging in whatsoever.

**Comment by MartinRBX** [comment]
Would you mind sending me how you login?
(Of course don't include sensitive information)

**Comment by DamnMerc** [comment]
``const rbx2 = new rbx({
  username: Config.user,
  password: Config.pass
})
rbx2.login().then(function() {
      console.log("Logged into ROBLOX!")
      Rbx_Ready.emit('begin')
    })
``

**Comment by MartinRBX** [comment]
What version of rblx-js do you have?
(Updated version is 1.0.0)


I followed your example, 
```JavaScript
const rbx = require('rblx-js');

var Config = {
    user: 'username',
    pass: 'password'
}

const rbx2 = new rbx({ username: Config.user, password: Config.pass })
rbx2.login().then(function () { console.log("Logged into ROBLOX!") })
``` 
It worked perfectly fine for me.

**Comment by DamnMerc** [comment]
It worked for me, its just for some reason out of the blue it'll throw that error up. No script line or anything.

**Comment by MartinRBX** [comment]
Probably because you have signed in too many times recently.
Feel free to reopen if this reoccurs.

**Comment by DamnMerc** [comment]
Issue isn't re-occuring but not being able to use some User functions. i.e getUserProfile.
